Update Alsa crate to 0.9.0
I updated my Raspberry Pi (but not the Kernel, since that one still has
the breaking change that breaks changing params), but without any
configuration changes, I now run into this crash:

    ALSA lib confmisc.c:1377:(snd_func_refer) Unable to find definition 'cards.2.pcm.front.0:CARD=2'
    ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
    ALSA lib conf.c:5727:(snd_config_expand) Evaluate error: No such file or directory
    ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM front:2
    thread 'playback' panicked at 'TODO: Failed to open device.: Error("snd_pcm_open", ENOENT)', src/playback.rs:358:50

The device is present, and I didn't change the configuration, so I
assume Alsa or the Kernel had a breaking change. But before I downgrade
again, maybe updating the Alsa crate fixes things? I don't have very
high hopes, but let's try. Also, this is one of the very few updates
that _removes_ dependencies, so that's a welcome change too.